// Code generated by go-swagger; DO NOT EDIT.

package user_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mantle-labs/console/models"
)

// GetBucketHealthOKCode is the HTTP code returned for type GetBucketHealthOK
const GetBucketHealthOKCode int = 200

/*
GetBucketHealthOK Bucket health returned successfully

swagger:response getBucketHealthOK
*/
type GetBucketHealthOK struct {

	/*
	  In: Body
	*/
	Payload *models.BucketHealthResponse `json:"body,omitempty"`
}

// NewGetBucketHealthOK creates GetBucketHealthOK with default headers values
func NewGetBucketHealthOK() *GetBucketHealthOK {

	return &GetBucketHealthOK{}
}

// WithPayload adds the payload to the get bucket health o k response
func (o *GetBucketHealthOK) WithPayload(payload *models.BucketHealthResponse) *GetBucketHealthOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bucket health o k response
func (o *GetBucketHealthOK) SetPayload(payload *models.BucketHealthResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBucketHealthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
